SELECT
    TRIP_DURATION,
    START_TIME,
    STOP_TIME,
    START_STATION_ID,
    START_STATION_NAME,
    START_STATION_LATITUDE,
    START_STATION_LONGITUDE,
    END_STATION_LATITUDE,
    END_STATION_LONGITUDE,
    END_STATION_ID,
    END_STATION_NAME,
    BIKE_ID
FROM
{{source('BIKE_TRIPS','BIKE_TRIPS_RAW')}} 
WHERE 
    SPLIT_PART(SPLIT_PART(START_TIME,' ',1),'/',1) = {{var('load_month')}}
    AND 
    SPLIT_PART(SPLIT_PART(START_TIME,' ',1),'/',2) = {{var('load_day')}}
LIMIT 99  -- Limited to fifty for simplicity

