SELECT 
    START_LOC_ZIPCODE, 
    NUMBER_OF_RIDES,
    RANK() OVER(ORDER BY NUMBER_OF_RIDES DESC) RANK
FROM (
SELECT 
    START_LOC_ZIPCODE, 
    COUNT(*) NUMBER_OF_RIDES
FROM {{ref('tfm_getzipcode')}}
GROUP BY START_LOC_ZIPCODE
)